config/routes.rb
Rails3Singletableinheritance::Application.routes.draw do
  resources :mobiles
  resources :samsung, :controller => 'mobiles', :type => "Samsung"
  resources :apple, :controller => 'mobiles', :type => "Apple"
  resources :htc, :controller => 'mobiles', :type => "HTC"
  resources :macromax, :controller => 'mobiles', :type => "Macromax"
  resources :users, :events do
	resources :comments
  end

  root :to => 'mobiles#index'

end

app/models/apple.rb
class Apple < Mobile
  # attr_accessible :title, :body
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true

  has_many :mobile_colors
  has_many :mobiles, :through => :mobile_colors
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment

  # belongs_to :imageable, :polymorphic => true
  belongs_to :commendable, :polymorphic => true
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :organizer, :place

  # has_many :pictures, :as => :imageable
  has_many :comments, :as => :commendable
end

app/models/htc.rb
class Htc < Mobile
  # attr_accessible :title, :body
end

app/models/micromax.rb
class Micromax < Mobile
  # attr_accessible :title, :body
end

app/models/mobile.rb
class Mobile < ActiveRecord::Base
  attr_accessible :manufacturer, :model, :operating_system, :type

  has_many :mobile_colors
  has_many :colors, :through => :mobile_colors
end

app/models/mobile_color.rb
class MobileColor < ActiveRecord::Base
  attr_accessible :color_id, :mobile_id

  belongs_to :color
  belongs_to :mobile
end

app/models/samsung.rb
class Samsung < Mobile
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  # has_many :pictures, :as => :imageable
  has_many :comments, :as => :commendable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	respond_to :html, :xml, :json
	before_filter :load_commendable

	def index
		@comments = @commendable.comments
	end

	def new
		@comment = @commendable.comments.new
	end

	def create
		@comment = @commendable.comments.new(params[:comment])
		if @comment.save
			flash[:notice] = "Successfully saved comment."
			respond_with(@commendable)
		else
			render 'new'
		end
	end

private
	def load_commendable
		resource, id = request.path.split('/')[1, 2]
		@commendable = resource.singularize.classify.constantize.find(id)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(params[:event])

		if @event.save
			respond_with(@event)
		else
			render :action => 'new'
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])

		if @event.update_attributes(params[:event])
		
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
	end
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@mobiles = params[:type] ? mobile_type.all : Mobile.all

		respond_with(@mobiles)
	end

	def new
		@mobile = mobile_type.new

		respond_with(@mobile)
	end

	def create
		@mobile = mobile_type.new(params[:mobile])

		if @mobile.save
			respond_with(@mobile)
		end
	end

	def show
		@mobile = Mobile.find(params[:id])
		respond_with(@mobile)
	end

	def edit
		@mobile = Mobile.find(params[:id])
		respond_with(@mobile)
	end

	def update
		@mobile = mobile_type.find(params[:mobile])

		if @mobile.update_attributes(params[:mobile])
		
		end
	end

	def destroy
	
	end

private
	def mobile_type
		params[:type].constantize
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :html, :xml, :json

	def index
		@users = User.all

		respond_with(@users)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			respond_with(@user)
		else
			render :action => 'new'
		end
	end

	def show
		@user = User.find(params[:id])

		respond_with(@user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(params[:user])
			respond_with(@user)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table border="1">
	<tr>
		<th> S.No. </th>
		<th>Comment</th>
	</tr>

	<% i = 1 %>
	<% @comments.each do |c| %>
		<tr>
			<td><%= i %></td>
			<td><%= c.comment %></td>
		</tr>
		<% i = i + 1 %>
	<% end %>
</table>


<p><%= link_to "New Comment", [:new, @commendable, :comment] %></p>
<p><%= link_to "Back", users_path %></p>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= form_for [@commendable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :comment, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Listing Events with Comments</h1>

<table border="1">
	<tr>
		<th>Name</th>
		<th>Organizer</th>
		<th>Place</th>
	</tr>

	<% @events.each do |event| %>
		<tr>
			<td><%= link_to event.name, event_path(event) %></td>
			<td><%= event.organizer %></td>
			<td><%= event.place %></td>
			<td><%= event.comments.first.comment if event.comments.any? %> <%= link_to "See All...", event_comments_path(event) %></td>
		</tr>
	<% end %>
</table>
<br /><br /><br />
<%= link_to "New Event", new_event_path %> | <%= link_to "All Users", users_path %>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
	<% if @event.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@event.errors.count, "error") %> prohibited
			this event from being saved:</h2>
			<ul>
				<% @event.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :organizer %><br />
    <%= f.text_field :organizer %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to "All Events", events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.comments.any? %>
	<h4> Listing Comments </h4>
	<% i = 1 %>
	<% @event.comments.each do |event_comment| %>
		<p><%= i %>. <%= event_comment.comment %></p>
		<% i = i + 1 %>
	<% end %>
<% else %>
	No Comments for this event "<em><%= @event.name %></em>"
<% end %>

<br /><br />
<%= link_to "Create a New Comment", new_event_comment_path(@event) %>
<br />
<%= link_to "Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3Singletableinheritance</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mobiles/edit.html.erb
<!-- Edit.html.erb -->

<%= form_for(@mobile, :as => :mobile) do |f| %>

<% end %>

app/views/mobiles/index.html.erb
<!-- index.html.erb -->

<h1>Listing Mobiles</h1>
 
<table>
	<tr>
		<th>Name</th>
		<th>Model</th>
		<th>Manufacturer</th>
		<th>Color</th>
		<th>Operating System</th>
	</tr>
 
	<% @mobiles.each do |mobile| %>
		<tr>
			<td><%= mobile.type %></td>
			<td><%= mobile.model %></td>
			<td><%= mobile.manufacturer %></td>
			<td></td>
			<td><%= mobile.operating_system %></td>
			<td><%= link_to 'Show', mobile %></td>
			<td><%= link_to 'Edit', edit_mobile_path(mobile) %></td>
			<td><%= link_to 'Destroy', mobile, :confirm => 'Are you sure?',
										 :method => :delete %></td>
		 </tr>
	<% end %>
</table>
 
<br />
 
<%= link_to 'Add a new Samsung device', new_samsung_path %> |
<%= link_to 'Add a new Apple device', new_apple_path %> |
<%= link_to 'Add a new Macromax device', new_macromax_path %> |
<%= link_to 'Add a new HTC device', new_htc_path %>

app/views/mobiles/new.html.erb
<!-- new.html.erb -->

<%= form_for(@mobile, :as => :mobile) do |f| %>
	<% if @mobile.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@mobile.errors.count, "error") %> prohibited
			this post from being saved:</h2>
			<ul>
				<% @mobile.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :operating_system %><br />
    <%= f.text_field :operating_system %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to "All Mobiles", mobiles_path %>

app/views/mobiles/show.html.erb
<!-- show.html.erb -->

<table border="1">
	<tr>
		<td>Model</td>
		<td><%= @mobile.model %></td>
	</tr>
	<tr>
		<td>Maunfacturer</td>
		<td><%= @mobile.manufacturer %></td>
	</tr>
	<tr>
		<td>Operating System</td>
		<td><%= @mobile.operating_system %></td>
	</tr>
</table>

<%= link_to "Edit", @mobile %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Listing Users with Comments</h1>

<table border="1">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Comments</th>
	</tr>

	<% @users.each do |user| %>
		<tr>
			<td><%= link_to user.name, user_path(user) %></td>
			<td><%= user.email %></td>
			<td><%= user.comments.first.comment if user.comments.any? %> <%= link_to "See All...", user_comments_path(user) %></td>
		</tr>
	<% end %>
</table>
<br /><br /><br />
<%= link_to "New User", new_user_path %> | <%= link_to "All Events", events_path %>

app/views/users/new.html.erb
<!-- new.html.erb -->

<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="errorExplanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited
			this user from being saved:</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to "All Users", users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.comments.any? %>
	<h4> Listing Comments </h4>
	<% i = 1 %>
	<% @user.comments.each do |user_comment| %>
		<p><%= i %>. <%= user_comment.comment %></p>
		<% i = i + 1 %>
	<% end %>
<% else %>
	No Comments for this User <%= @user.name %>
<% end %>

<br /><br />
<%= link_to "Create a New Comment", new_user_comment_path(@user) %>
<br />
<%= link_to "Users", users_path %>